# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'RoleChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RoleChat	
 	pod 'Fabric’
	pod 'Crashlytics’
	pod 'SideMenuController'
  	pod 'SlackTextViewController'
	pod 'MobilePlayer'
  	pod 'SimpleImageViewer'
	pod 'RCMarkdownParser'
	pod 'Realm’
	pod 'SDWebImage’
	pod '1PasswordExtension'
	pod 'YYKit', '~> 1.0.9'
	pod 'MJRefresh'
	pod 'SDWebImage'
	pod 'TTTAttributedLabel'
	pod 'Qiniu'
	pod 'MJExtension'
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'Masonry’
	pod 'SocketRocket'
    pod 'SGQRCode'

  target 'RoleChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoleChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.1'
    end
  end
end
